### PR TITLE
fix: trino show tables needs 404 instead of 403

### LINKED ISSUE #1060: View not found or action can_get_metadata forbidden for Principal
**Description**

When configuring metabase to sync metadata from lakekeeper using the following query: ```SHOW TABLES FROM "lakekeeper_dev"."system"```, we see these logs in the lakekeeper pod ```"View not found or action can_get_metadata forbidden for Principal(oidc~{GUID})"```

**System Information:**
 - Deployment Type: helm chart
 - Lakekeeper Version: 0.8.3
 - Authentication Provider: EntraID
 - Authorization Provider: OpenFGA

**full log line**
```
{"timestamp":"2025-04-30T14:47:53.002601Z","level":"INFO","message":"Error response","error_id":"0196872b-21aa-7770-aa28-c18acc41d0d1","stack_s":"View not found or action can_get_metadata forbidden for Principal(oidc~{GUID})","details":"[]","message":"View not found or action can_get_metadata forbidden for Principal(oidc~85ce0e1f-24ef-4d00-8a3a-303421bc2bd9)","r#type":"ViewActionForbidden","code":"404","target":"iceberg_ext::catalog::rest::error","filename":"crates/iceberg-ext/src/catalog/rest/error.rs","line_number":252,"span":{"method":"GET","request_id":"b1cc4ca9757d0e14f3d724b2fb0c7fc4","uri":"/catalog/v1/13817976-1ac4-11f0-9bfe-d7e553d0e1cb/namespaces/slurm/views/hpc_stats","version":"HTTP/1.1","name":"request"},"spans":[{"method":"GET","request_id":"b1cc4ca9757d0e14f3d724b2fb0c7fc4","uri":"/catalog/v1/13817976-1ac4-11f0-9bfe-d7e553d0e1cb/namespaces/slurm/views/hpc_stats","version":"HTTP/1.1","name":"request"}]}
```

### PR DESCRIPTION
**Pull request by twuebi**
fixes #1060

### CODE REVIEW

File: crates/iceberg-catalog/src/service/authz/mod.rs [hunk 1]
```diff
@@ -486,7 +486,7 @@ where
         match namespace_id {
             Ok(None) => {
                 tracing::debug!("Namespace not found, returning forbidden.");
```
Comment (c-thiel) [inline crates/iceberg-catalog/src/service/authz/mod.rs:488]:
```suggestion
                tracing::debug!("Namespace not found.");
```

**Review by c-thiel — APPROVED** [review]
